// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSZmOps4XpCzABwTPTnLqhLbYYRfs30vA',
    appId: '1:920488454265:web:cdf540afb7d88146fb8ca8',
    messagingSenderId: '920488454265',
    projectId: 'grocery-app-f1ffe',
    authDomain: 'grocery-app-f1ffe.firebaseapp.com',
    storageBucket: 'grocery-app-f1ffe.appspot.com',
    measurementId: 'G-NKRX6MW7EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4TvqKUmbM7vF2OfIJKlnDarPY9cq9OLE',
    appId: '1:920488454265:android:ea8290addaa1b054fb8ca8',
    messagingSenderId: '920488454265',
    projectId: 'grocery-app-f1ffe',
    storageBucket: 'grocery-app-f1ffe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaLvKtStEWJ1p9bXrClanmKdSPh2mzddk',
    appId: '1:920488454265:ios:a6a1efa74d14c574fb8ca8',
    messagingSenderId: '920488454265',
    projectId: 'grocery-app-f1ffe',
    storageBucket: 'grocery-app-f1ffe.appspot.com',
    iosClientId: '920488454265-4vk8io87p9sjo5phiaho2jjfj3apr7dt.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryStrore',
  );
}
